# JEKYLL
exclude: [".gitignore", ".git", "config.rb", "package.json", "Gruntfile.js", "bower_components", ".travis.yml", "ai", "src", "VERSION", "LICENSE", "README.md", "icon.png", "node_modules"]

destination: ./_site

url: http://ink.sapo.pt/
environment: production
description: Ink is a set of tools for quick development of web interfaces.
timezone: Europe/Lisbon

# SITE TITLE
title: Ink Interface Kit

# INK LATEST VERSION
version: 3.0.5

# URLS
download_url: https://github.com/sapo/Ink/releases/download/
download_src_url: https://github.com/sapo/Ink/archive/
repo_url: https://github.com/sapo/Ink/
cdn_url: http://cdn.ink.sapo.pt/

# ASSETS PATHS
images_path: /assets/img/
js_path: /assets/js/
css_path: /assets/css/

sections:
  - title: UI Elements
    components:
      - title: Grid
        topics:
          - title: Basic principles
          - title: Dividing space
          - title: Gutters
          - title: Multiple screen sizes
      - title: Navigation
        topics:
          - title: Basic principles
          - title: Menus
          - title: Breadcrumbs
          - title: Pagination
          - title: Pills
          - title: Dropdowns
      - title: Typography
        topics:
          - title: Basic principles
          - title: Fonts
          - title: Headings and paragraphs
          - title: Lists
          - title: Hypertext
          - title: Emphasis
          - title: "Notes, blockquotes and addresses"
          - title: Labels and badges
          - title: Utility classes
      - title: Images
        topics:
          - title: Basic principles
          - title: Captions
          - title: Targeting multiple devices
      - title: Tables
        topics:
          - title: Basic principles
          - title: Usage
          - title: Alternating row colors
          - title: Highlighting rows
          - title: Borders
          - title: Row colors
          - title: Combining styles
      - title: Forms
        topics:
          - title: Basic principles
          - title: Block forms
          - title: Inline forms
          - title: Required fields and warnings
          - title: Appended and prepended inputs
          - title: Checkboxes and radio buttons
      - title: Buttons
        topics:
          - title: Basic principles
          - title: Button groups
          - title: Button toolbars
      - title: Alerts
        topics:
          - title: Basic principles
          - title: Basic alerts
          - title: Block alerts
      - title: Helpers
        topics:
          - title: Basic principles
          - title: Element alignment
          - title: Content alignment
          - title: Element spacing
          - title: Element visibility
      - title: Flexbox
        topics:
          - title: Basic principles
          - title: Element alignment
          - title: Content alignment
          - title: Reordering
  - title: Javascript
    components:
      - title: User interface
        topics:
          - title: Ink.Autoload
          - title: Ink.UI.Animate
          - title: Ink.UI.Carousel
          - title: Ink.UI.Close
          - title: Ink.UI.Common
          - title: Ink.UI.DatePicker
          - title: Ink.UI.Draggable
          - title: Ink.UI.Drawer
          - title: Ink.UI.Dropdown
          - title: Ink.UI.Droppable
          - title: Ink.UI.FormValidator
          - title: Ink.UI.FormValidator.2
          - title: Ink.UI.ImageQuery
          - title: Ink.UI.LazyLoad
          - title: Ink.UI.Modal
          - title: Ink.UI.Pagination
          - title: Ink.UI.ProgressBar
          - title: Ink.UI.SmoothScroller
          - title: Ink.UI.SortableList
          - title: Ink.UI.Spy
          - title: Ink.UI.Stacker
          - title: Ink.UI.Sticky
          - title: Ink.UI.Swipe
          - title: Ink.UI.Table
          - title: Ink.UI.Tabs
          - title: Ink.UI.Toggle
          - title: Ink.UI.Tooltip
          - title: Ink.UI.TreeView
      - title: Core
        topics:
          - title: Ink
      - title: Dom manipulation
        topics:
          - title: Ink.Dom.Browser
          - title: Ink.Dom.Css
          - title: Ink.Dom.Element
          - title: Ink.Dom.Event
          - title: Ink.Dom.FormSerialize
          - title: Ink.Dom.Loaded
          - title: Ink.Dom.Selector
      - title: Network communication
        topics:
          - title: Ink.Net.Ajax
          - title: Ink.Net.JsonP
      - title: Utilities
        topics:
          - title: Ink.Util.Array
          - title: Ink.Util.Cookie
          - title: Ink.Util.Date
          - title: Ink.Util.Dumper
          - title: Ink.Util.I18n
          - title: Ink.Util.Json
          - title: Ink.Util.String
          - title: Ink.Util.Url
          - title: Ink.Util.Validator
  - title: Cookbook
  - title: Glossary

releases:
  - 3.0.0
  - 2.3.2
  - 2.3.1
  - 2.3.0
  - 2.2.1
  - 2.2.0
  - 2.1.1
  - 2.1.0
  - 2.0.0
  - 1.1.0
  - 0.1.0

# ANALYTICS
analytics: FC2C65EF-D60C-4BC2-9D76-251A50DADC3D
markdown: kramdown
